module.exports = {
  cronModel: require('./cronModel'),
  dealModel: require('./dealModel'),
  escrowModel: require('./escrow'),
  gameModel: require('./gameModel'),
  gamePlayerModel: require('./gamePlayerModel'),
  productModel: require('./productModel'),
  revenueModel: require('./revenueModel'),
  revenueStagesModel: require('./revenueStagesModel'),
  rewardModel: require('./rewardModel'),
  smartContractModel: require('./smartContractModel'),
  tokenizedRewardModel: require('./tokenizedRewardModel'),
  transferModel: require('./transferModel'),
  userModel: require('./userModel'),
  assetModel: require('./assetModel'),
  assetCategoriesModel: require('./assetCategoriesModel'),
  propModel: require('./propModel'),
  propCategoriesModel: require('./propCategoriesModel'),
  gameCategoryModel: require('./gameCategoryModel'),
  ageCategoryModel: require('./ageCategoryModel'),
  ESRBCategoryModel: require('./ESRBCategoryModel'),
  genreModel: require('./genreModel'),
  productCategoriesModel: require('./productCategoriesModel'),
  minTtransactionsModel: require('./mintTransactionsModel')
}
